import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css";
import Header from "@/components/header/header";
import RecoilRootWrapper from "@/recoil/RecoilRoot";
import StyledComponentsRegistry from "@/lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "프론트 엔드 노수혁 포트 폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <RecoilRootWrapper>
            <Header />
            {children}
          </RecoilRootWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
