import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css";
import Scrolls from "@/components/scroll";
import Header from "@/components/header/header";
import RecoilRootWrapper from "@/recoil/RecoilRoot";
import { Suspense } from "react";
import StyledComponentsRegistry from "@/lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "프론트 엔드 노수혁 포트 폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Suspense fallback={<h1>새로 고침 중 </h1>}>
            <RecoilRootWrapper>
              <Header />
              <Scrolls />
              {children}
            </RecoilRootWrapper>
          </Suspense>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
